import type { Metadata } from "next";
import Link from "next/link";
import { RoastResultView } from "@/components/features/roast/roast-result-view";
import { FadeIn } from "@/components/motion/fade-in";
import { Button } from "@/components/ui/button";
import { getRoastResultById } from "@/lib/roast-server";

interface RoastResultPageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: RoastResultPageProps): Promise<Metadata> {
  const { id } = await params;
  const roast = await getRoastResultById(id);
  const shortId = id.slice(0, 8);
  const imagePath = `/roast/${encodeURIComponent(id)}/opengraph-image`;

  if (!roast) {
    return {
      title: `Roast Report ${shortId} — Corsair`,
      description: `Roast result ${shortId} generated by Corsair trust center scanner.`,
      openGraph: {
        title: `Roast Report ${shortId} — Corsair`,
        description: `Roast result ${shortId} generated by Corsair trust center scanner.`,
        type: "article",
        url: `/roast/${id}`,
        images: [
          {
            url: imagePath,
            width: 1200,
            height: 630,
            alt: `Roast report ${shortId}`,
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: `Roast Report ${shortId} — Corsair`,
        description: `Roast result ${shortId} generated by Corsair trust center scanner.`,
        images: [imagePath],
      },
    };
  }

  const score = roast.compositeScore.toFixed(1);
  const title = `${roast.domain} — ${roast.verdict} (${score}/10)`;
  const description =
    `Corsair roast report for ${roast.domain}. Verdict: ${roast.verdict}. ` +
    `Composite score: ${score}/10 across discoverability, verifiability, freshness, machine-readability, and transparency.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      url: `/roast/${id}`,
      images: [
        {
          url: imagePath,
          width: 1200,
          height: 630,
          alt: `Roast report for ${roast.domain}`,
        },
      ],
      publishedTime: roast.createdAt,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [imagePath],
    },
  };
}

export default async function RoastResultPage({ params }: RoastResultPageProps) {
  const { id } = await params;

  return (
    <main className="px-6 py-16">
      <div className="mx-auto max-w-5xl space-y-6">
        <FadeIn>
          <div className="flex flex-wrap items-end justify-between gap-3">
            <div>
              <p className="font-pixel text-[7px] tracking-wider text-corsair-gold/60">
                SAVED REPORT
              </p>
              <h1 className="mt-1 font-display text-3xl font-bold text-corsair-text">Trust Center Roast</h1>
              <p className="mt-1 font-mono text-xs text-corsair-text-dim">ID: {id}</p>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button asChild variant="outline" size="sm" className="font-mono text-[10px]">
                <Link href="/roast">Run another roast</Link>
              </Button>
              <Button asChild size="sm" className="font-mono text-[10px]">
                <Link href="/publish">Generate trust.txt</Link>
              </Button>
            </div>
          </div>
        </FadeIn>

        <FadeIn delay={0.1}>
          <RoastResultView id={id} />
        </FadeIn>
      </div>
    </main>
  );
}
