export function generateTrustTxtExample(domain: string): string {
  const expires = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000)
    .toISOString()
    .replace(/\.[0-9]{3}Z$/, "Z");

  return [
    `# trust.txt example for ${domain}`,
    "# Generated by Corsair Roast",
    "",
    `DID: did:web:${domain}`,
    `CPOE: https://${domain}/.well-known/cpoes/soc2-latest.jwt`,
    `CPOE: https://${domain}/.well-known/cpoes/pentest-latest.jwt`,
    `SCITT: https://${domain}/scitt/entries`,
    `FLAGSHIP: https://${domain}/ssf/streams`,
    `CATALOG: https://${domain}/.well-known/compliance-catalog.json`,
    "Frameworks: SOC2, ISO27001",
    `Contact: security@${domain}`,
    `Expires: ${expires}`,
    "",
    "# To publish for real:",
    "# corsair trust-txt generate --did did:web:<your-domain>",
    "",
  ].join("\n");
}
