# =============================================================================
# Corsair CPOE Pipeline for GitLab CI
# =============================================================================
#
# This template adds compliance signing + drift detection to your GitLab pipeline.
# Each pipeline run:
#   1. Runs GitLab security scans (SAST, dependency scanning, etc.)
#   2. Signs the results as a CPOE (JWT-VC) with `corsair sign`
#   3. Compares against the previous CPOE with `corsair drift`
#   4. Stores the CPOE as a pipeline artifact for the next run
#
# Setup:
#   1. Generate keypair: corsair keygen --output ./keys
#   2. Add corsair-signing.key as a CI/CD variable (CORSAIR_PRIVATE_KEY, file type)
#   3. Store corsair-signing.pub in the repo at ./keys/corsair-signing.pub
#   4. Include this template in your .gitlab-ci.yml
#
# Usage:
#   include:
#     - local: 'examples/gitlab-ci-corsair.yml'
#
# Or copy the stages below into your existing .gitlab-ci.yml.
# =============================================================================

stages:
  - test
  - security
  - compliance

# =============================================================================
# Stage 1: GitLab Security Scans (built-in)
# =============================================================================

# Include GitLab's built-in security scanning templates.
# These produce gl-sast-report.json, gl-dependency-scanning-report.json, etc.
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  # Optional — add more as needed:
  # - template: Security/Container-Scanning.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml

# =============================================================================
# Stage 2: Sign as CPOE
# =============================================================================

corsair-sign:
  stage: compliance
  image: oven/bun:1
  needs:
    - job: semgrep-sast
      artifacts: true
    - job: gemnasium-dependency_scanning
      artifacts: true
      optional: true
  before_script:
    # Install corsair (or use a pre-built image)
    - bun install --global corsair
    # Write the signing key from CI/CD variable
    - mkdir -p keys
    - cp $CORSAIR_PRIVATE_KEY keys/corsair-signing.key
  script:
    # Sign the SAST report as a CPOE
    - |
      if [ -f gl-sast-report.json ]; then
        corsair sign \
          --file gl-sast-report.json \
          --key-dir ./keys \
          --did "did:web:${CI_PROJECT_ROOT_NAMESPACE}.gitlab.io" \
          --scope "${CI_PROJECT_NAME} SAST — ${CI_COMMIT_SHORT_SHA}" \
          --output cpoe-sast.jwt
        echo "SAST CPOE signed: cpoe-sast.jwt"
      fi

    # Sign dependency scanning report if available
    - |
      if [ -f gl-dependency-scanning-report.json ]; then
        corsair sign \
          --file gl-dependency-scanning-report.json \
          --key-dir ./keys \
          --did "did:web:${CI_PROJECT_ROOT_NAMESPACE}.gitlab.io" \
          --scope "${CI_PROJECT_NAME} Dependency Scan — ${CI_COMMIT_SHORT_SHA}" \
          --output cpoe-deps.jwt
        echo "Dependency CPOE signed: cpoe-deps.jwt"
      fi
  artifacts:
    paths:
      - cpoe-sast.jwt
      - cpoe-deps.jwt
    expire_in: 90 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# =============================================================================
# Stage 3: Drift Detection
# =============================================================================

corsair-drift:
  stage: compliance
  image: oven/bun:1
  needs:
    - job: corsair-sign
      artifacts: true
  before_script:
    - bun install --global corsair
    # Download previous CPOE from the last successful pipeline
    # Uses GitLab's API to fetch artifacts from the previous pipeline
    - |
      PREV_PIPELINE=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines?status=success&ref=${CI_DEFAULT_BRANCH}&per_page=2" \
        | bun -e 'const d=await Bun.stdin.json();console.log(d[1]?.id||"")')
    - |
      if [ -n "$PREV_PIPELINE" ]; then
        curl -s --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/artifacts/${CI_DEFAULT_BRANCH}/download?job=corsair-sign" \
          -o prev-artifacts.zip 2>/dev/null && unzip -o prev-artifacts.zip -d prev/ 2>/dev/null || true
      fi
  script:
    - |
      if [ -f cpoe-sast.jwt ] && [ -f prev/cpoe-sast.jwt ]; then
        echo "Comparing SAST CPOEs..."
        corsair drift --current cpoe-sast.jwt --previous prev/cpoe-sast.jwt || DRIFT_DETECTED=1
      else
        echo "No previous SAST CPOE found — skipping drift check (first run)"
      fi

    - |
      if [ -f cpoe-deps.jwt ] && [ -f prev/cpoe-deps.jwt ]; then
        echo "Comparing Dependency CPOEs..."
        corsair drift --current cpoe-deps.jwt --previous prev/cpoe-deps.jwt || DRIFT_DETECTED=1
      fi

    # Fail the pipeline if regression detected (optional — remove for advisory-only)
    - |
      if [ "$DRIFT_DETECTED" = "1" ]; then
        echo "COMPLIANCE REGRESSION DETECTED — see drift report above"
        exit 1
      fi
  allow_failure: true  # Set to false to block merges on regression
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
